//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int id_log { get; set; }
        public Nullable<int> id_user { get; set; }
        public string action { get; set; }
        public string entity_type { get; set; }
        public Nullable<int> entity_id { get; set; }
        public string details { get; set; }
        public System.DateTime timestamp { get; set; }
    }
}
