//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BankSystemEntities1 : DbContext
    {
        public BankSystemEntities1()
            : base("name=BankSystemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Transactions> Transactions { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
    
        public virtual ObjectResult<sp_AuthenticateUser_Result> sp_AuthenticateUser(string login, string password_hash)
        {
            var loginParameter = login != null ?
                new ObjectParameter("login", login) :
                new ObjectParameter("login", typeof(string));
    
            var password_hashParameter = password_hash != null ?
                new ObjectParameter("password_hash", password_hash) :
                new ObjectParameter("password_hash", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_AuthenticateUser_Result>("sp_AuthenticateUser", loginParameter, password_hashParameter);
        }
    
        public virtual int sp_CreateClient(string client_type, string full_name, string passport_inn, string phone, string email, string address, Nullable<int> user_id, ObjectParameter new_client_id, ObjectParameter new_account_number)
        {
            var client_typeParameter = client_type != null ?
                new ObjectParameter("client_type", client_type) :
                new ObjectParameter("client_type", typeof(string));
    
            var full_nameParameter = full_name != null ?
                new ObjectParameter("full_name", full_name) :
                new ObjectParameter("full_name", typeof(string));
    
            var passport_innParameter = passport_inn != null ?
                new ObjectParameter("passport_inn", passport_inn) :
                new ObjectParameter("passport_inn", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CreateClient", client_typeParameter, full_nameParameter, passport_innParameter, phoneParameter, emailParameter, addressParameter, user_idParameter, new_client_id, new_account_number);
        }
    
        public virtual ObjectResult<sp_TransferMoney_Result> sp_TransferMoney(string from_account, string to_account, Nullable<decimal> amount, string description, Nullable<int> user_id)
        {
            var from_accountParameter = from_account != null ?
                new ObjectParameter("from_account", from_account) :
                new ObjectParameter("from_account", typeof(string));
    
            var to_accountParameter = to_account != null ?
                new ObjectParameter("to_account", to_account) :
                new ObjectParameter("to_account", typeof(string));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(decimal));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TransferMoney_Result>("sp_TransferMoney", from_accountParameter, to_accountParameter, amountParameter, descriptionParameter, user_idParameter);
        }
    }
}
