//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public int id_transaction { get; set; }
        public System.DateTime transaction_date { get; set; }
        public string type { get; set; }
        public Nullable<int> from_account { get; set; }
        public Nullable<int> to_account { get; set; }
        public decimal amount { get; set; }
        public string description { get; set; }
        public string status { get; set; }
        public Nullable<decimal> commission { get; set; }
        public Nullable<int> created_by { get; set; }
        public bool is_deleted { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual Accounts Accounts1 { get; set; }
    }
}
