//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int id_user { get; set; }
        public string login { get; set; }
        public string password_hash { get; set; }
        public string email { get; set; }
        public int id_role { get; set; }
        public bool is_active { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
